name: Complie LogonDetails.exe

on:
  push:
    branches:
      - 'main'

jobs:
  changes:
    name: Check for Changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      build: ${{ steps.filter.outputs.build }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Check for Changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            build:
              - './UK/LogonDetails.py'

  build-exe:
    name: Build EXE
    runs-on: windows-latest
    needs: changes
    if: ${{ needs.changes.outputs.build == 'true' }}
    concurrency:
      group: uk-controller-pack-build-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install pyinstaller

      - name: Run Python Script
        run: pyinstaller --distpath ./UK/ --onefile -n LogonDetails.exe ./UK/LogonDetails.py

      - name: Commit exe File
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./UK/LogonDetails.exe
          git commit -m "Update LogonDetails.exe"
          git push
