name: 🛰️ TopSky Shared Data File Compilation

on:
  push:
    paths:
      - '.data/TopSky Shared/**'
      - '.github/workflows/TopSky-Compiler.yml'
      - 'workflows/TopSky/compiler.py'
  pull_request:
    types: [opened, synchronize]
    paths:
      - '.data/TopSky Shared/**'
      - '.github/workflows/TopSky-Compiler.yml'
      - 'workflows/TopSky/compiler.py'

concurrency:
  group: TopSky-Data-Compile
  cancel-in-progress: true

jobs:
  Compile_TopSky_Data:
    if: ${{ ! contains(github.event.head_commit.message, 'Compile TopSky shared data files') }} # Checks last commit is not done by the bot, format required else it throws an error
    runs-on: ubuntu-latest

    steps:
      - name: 🧰 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
      
      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: 🧪 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r workflows/TopSky/requirements.txt

      - name: 🔎 Run tests
        run: python -m pytest workflows/TopSky/tests/
      
      - name: 🏗️ Run TopSky shared data files compiler
        run: python workflows/TopSky/compiler.py 
      
      - name: ⬆️ Commit and push TopSky shared data file changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add .
          git commit -m 'Chore: Compile TopSky shared data files'
          git push
