name: TopSky Data Files

on: 
  push:
    paths:
      - 'UK/Data/Plugin/TopSky_NERC/ICAO_Aircraft.json'
      - 'UK/Data/Plugin/TopSky_iTEC/ICAO_Aircraft.json'
      - 'UK/Data/Plugin/TopSky_NODE/ICAO_Aircraft.json'
      - 'UK/Data/Plugin/TopSky_NOVA/ICAO_Aircraft.json'
      - 'UK/Data/Plugin/TopSky_NERC/ICAO_Aircraft.txt'
      - 'UK/Data/Plugin/TopSky_iTEC/ICAO_Aircraft.txt'
      - 'UK/Data/Plugin/TopSky_NODE/ICAO_Aircraft.txt'
      - 'UK/Data/Plugin/TopSky_NOVA/ICAO_Aircraft.txt'
      - 'UK/Data/Plugin/TopSky_NERC/ICAO_Airlines.txt'
      - 'UK/Data/Plugin/TopSky_iTEC/ICAO_Airlines.txt'
      - 'UK/Data/Plugin/TopSky_NODE/ICAO_Airlines.txt'
      - 'UK/Data/Plugin/TopSky_NOVA/ICAO_Airlines.txt'
      - 'UK/Data/Plugin/TopSky_NERC/ICAO_Airports.txt'
      - 'UK/Data/Plugin/TopSky_iTEC/ICAO_Airports.txt'
      - 'UK/Data/Plugin/TopSky_NODE/ICAO_Airports.txt'
      - 'UK/Data/Plugin/TopSky_NOVA/ICAO_Airports.txt'
      - 'UK/Data/Plugin/TopSky_NERC/TopSkyAirspace.txt'
      - 'UK/Data/Plugin/TopSky_iTEC/TopSkyAirspace.txt'
      - 'UK/Data/Plugin/TopSky_NODE/TopSkyAirspace.txt'
      - 'UK/Data/Plugin/TopSky_NOVA/TopSkyAirspace.txt'
      - 'UK/Data/Plugin/TopSky_NERC/TopSkyAreas.txt'
      - 'UK/Data/Plugin/TopSky_iTEC/TopSkyAreas.txt'
      - 'UK/Data/Plugin/TopSky_NODE/TopSkyAreas.txt'
      - 'UK/Data/Plugin/TopSky_NOVA/TopSkyAreas.txt'
      - 'UK/Data/Plugin/TopSky_NERC/TopSkyCallsigns.txt'
      - 'UK/Data/Plugin/TopSky_iTEC/TopSkyCallsigns.txt'
      - 'UK/Data/Plugin/TopSky_NODE/TopSkyCallsigns.txt'
      - 'UK/Data/Plugin/TopSky_NOVA/TopSkyCallsigns.txt'
      - 'UK/Data/Plugin/TopSky_NERC/TopSkyCallsignsLocal.txt'
      - 'UK/Data/Plugin/TopSky_iTEC/TopSkyCallsignsLocal.txt'
      - 'UK/Data/Plugin/TopSky_NODE/TopSkyCallsignsLocal.txt'
      - 'UK/Data/Plugin/TopSky_NOVA/TopSkyCallsignsLocal.txt'
      - 'UK/Data/Plugin/TopSky_NERC/TopSkyCPDLC.txt'
      - 'UK/Data/Plugin/TopSky_iTEC/TopSkyCPDLC.txt'
      - 'UK/Data/Plugin/TopSky_NODE/TopSkyCPDLC.txt'
      - 'UK/Data/Plugin/TopSky_NOVA/TopSkyCPDLC.txt'
      - 'UK/Data/Plugin/TopSky_NERC/TopSkyCPDLChoppieCode.txt'
      - 'UK/Data/Plugin/TopSky_iTEC/TopSkyCPDLChoppieCode.txt'
      - 'UK/Data/Plugin/TopSky_NODE/TopSkyCPDLChoppieCode.txt'
      - 'UK/Data/Plugin/TopSky_NOVA/TopSkyCPDLChoppieCode.txt'
      - 'UK/Data/Plugin/TopSky_NERC/TopSkyMaps.txt'
      - 'UK/Data/Plugin/TopSky_iTEC/TopSkyMaps.txt'
      - 'UK/Data/Plugin/TopSky_NODE/TopSkyMaps.txt'
      - 'UK/Data/Plugin/TopSky_NOVA/TopSkyMaps.txt'
      - 'UK/Data/Plugin/TopSky_NERC/TopSkyMSAW.txt'
      - 'UK/Data/Plugin/TopSky_iTEC/TopSkyMSAW.txt'
      - 'UK/Data/Plugin/TopSky_NODE/TopSkyMSAW.txt'
      - 'UK/Data/Plugin/TopSky_NOVA/TopSkyMSAW.txt'
      - 'UK/Data/Plugin/TopSky_NERC/TopSkyRadars.txt'
      - 'UK/Data/Plugin/TopSky_iTEC/TopSkyRadars.txt'
      - 'UK/Data/Plugin/TopSky_NODE/TopSkyRadars.txt'
      - 'UK/Data/Plugin/TopSky_NOVA/TopSkyRadars.txt'
  pull_request:
    paths:
      - 'UK/Data/Plugin/TopSky_NERC/ICAO_Aircraft.json'
      - 'UK/Data/Plugin/TopSky_iTEC/ICAO_Aircraft.json'
      - 'UK/Data/Plugin/TopSky_NODE/ICAO_Aircraft.json'
      - 'UK/Data/Plugin/TopSky_NOVA/ICAO_Aircraft.json'
      - 'UK/Data/Plugin/TopSky_NERC/ICAO_Aircraft.txt'
      - 'UK/Data/Plugin/TopSky_iTEC/ICAO_Aircraft.txt'
      - 'UK/Data/Plugin/TopSky_NODE/ICAO_Aircraft.txt'
      - 'UK/Data/Plugin/TopSky_NOVA/ICAO_Aircraft.txt'
      - 'UK/Data/Plugin/TopSky_NERC/ICAO_Airlines.txt'
      - 'UK/Data/Plugin/TopSky_iTEC/ICAO_Airlines.txt'
      - 'UK/Data/Plugin/TopSky_NODE/ICAO_Airlines.txt'
      - 'UK/Data/Plugin/TopSky_NOVA/ICAO_Airlines.txt'
      - 'UK/Data/Plugin/TopSky_NERC/ICAO_Airports.txt'
      - 'UK/Data/Plugin/TopSky_iTEC/ICAO_Airports.txt'
      - 'UK/Data/Plugin/TopSky_NODE/ICAO_Airports.txt'
      - 'UK/Data/Plugin/TopSky_NOVA/ICAO_Airports.txt'
      - 'UK/Data/Plugin/TopSky_NERC/TopSkyAirspace.txt'
      - 'UK/Data/Plugin/TopSky_iTEC/TopSkyAirspace.txt'
      - 'UK/Data/Plugin/TopSky_NODE/TopSkyAirspace.txt'
      - 'UK/Data/Plugin/TopSky_NOVA/TopSkyAirspace.txt'
      - 'UK/Data/Plugin/TopSky_NERC/TopSkyAreas.txt'
      - 'UK/Data/Plugin/TopSky_iTEC/TopSkyAreas.txt'
      - 'UK/Data/Plugin/TopSky_NODE/TopSkyAreas.txt'
      - 'UK/Data/Plugin/TopSky_NOVA/TopSkyAreas.txt'
      - 'UK/Data/Plugin/TopSky_NERC/TopSkyCallsigns.txt'
      - 'UK/Data/Plugin/TopSky_iTEC/TopSkyCallsigns.txt'
      - 'UK/Data/Plugin/TopSky_NODE/TopSkyCallsigns.txt'
      - 'UK/Data/Plugin/TopSky_NOVA/TopSkyCallsigns.txt'
      - 'UK/Data/Plugin/TopSky_NERC/TopSkyCallsignsLocal.txt'
      - 'UK/Data/Plugin/TopSky_iTEC/TopSkyCallsignsLocal.txt'
      - 'UK/Data/Plugin/TopSky_NODE/TopSkyCallsignsLocal.txt'
      - 'UK/Data/Plugin/TopSky_NOVA/TopSkyCallsignsLocal.txt'
      - 'UK/Data/Plugin/TopSky_NERC/TopSkyCPDLC.txt'
      - 'UK/Data/Plugin/TopSky_iTEC/TopSkyCPDLC.txt'
      - 'UK/Data/Plugin/TopSky_NODE/TopSkyCPDLC.txt'
      - 'UK/Data/Plugin/TopSky_NOVA/TopSkyCPDLC.txt'
      - 'UK/Data/Plugin/TopSky_NERC/TopSkyCPDLChoppieCode.txt'
      - 'UK/Data/Plugin/TopSky_iTEC/TopSkyCPDLChoppieCode.txt'
      - 'UK/Data/Plugin/TopSky_NODE/TopSkyCPDLChoppieCode.txt'
      - 'UK/Data/Plugin/TopSky_NOVA/TopSkyCPDLChoppieCode.txt'
      - 'UK/Data/Plugin/TopSky_NERC/TopSkyMaps.txt'
      - 'UK/Data/Plugin/TopSky_iTEC/TopSkyMaps.txt'
      - 'UK/Data/Plugin/TopSky_NODE/TopSkyMaps.txt'
      - 'UK/Data/Plugin/TopSky_NOVA/TopSkyMaps.txt'
      - 'UK/Data/Plugin/TopSky_NERC/TopSkyMSAW.txt'
      - 'UK/Data/Plugin/TopSky_iTEC/TopSkyMSAW.txt'
      - 'UK/Data/Plugin/TopSky_NODE/TopSkyMSAW.txt'
      - 'UK/Data/Plugin/TopSky_NOVA/TopSkyMSAW.txt'
      - 'UK/Data/Plugin/TopSky_NERC/TopSkyRadars.txt'
      - 'UK/Data/Plugin/TopSky_iTEC/TopSkyRadars.txt'
      - 'UK/Data/Plugin/TopSky_NODE/TopSkyRadars.txt'
      - 'UK/Data/Plugin/TopSky_NOVA/TopSkyRadars.txt'


jobs:
  Check_Files_Match:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if ICAO_Aircraft.json files match
        run: |
          file1="UK/Data/Plugin/TopSky_NERC/ICAO_Aircraft.json"
          file2="UK/Data/Plugin/TopSky_iTEC/ICAO_Aircraft.json"
          file3="UK/Data/Plugin/TopSky_NODE/ICAO_Aircraft.json"
          file4="UK/Data/Plugin/TopSky_NOVA/ICAO_Aircraft.json"
          
          if ! cmp --silent "$file1" "$file2" || ! cmp --silent "$file1" "$file3" || ! cmp --silent "$file1" "$file4"; then
            echo "ICAO_Aircraft.json files do not match!"
            exit 1
          fi
        shell: bash

      - name: Check if ICAO_Aircraft.txt files match
        run: |
          file1="UK/Data/Plugin/TopSky_NERC/ICAO_Aircraft.txt"
          file2="UK/Data/Plugin/TopSky_iTEC/ICAO_Aircraft.txt"
          file3="UK/Data/Plugin/TopSky_NODE/ICAO_Aircraft.txt"
          file4="UK/Data/Plugin/TopSky_NOVA/ICAO_Aircraft.txt"
          
          if ! cmp --silent "$file1" "$file2" || ! cmp --silent "$file1" "$file3" || ! cmp --silent "$file1" "$file4"; then
            echo "ICAO_Aircraft.txt files do not match!"
            exit 1
          fi
        shell: bash

      - name: Check if ICAO_Airlines.txt files match
        run: |
          file1="UK/Data/Plugin/TopSky_NERC/ICAO_Airlines.txt"
          file2="UK/Data/Plugin/TopSky_iTEC/ICAO_Airlines.txt"
          file3="UK/Data/Plugin/TopSky_NODE/ICAO_Airlines.txt"
          file4="UK/Data/Plugin/TopSky_NOVA/ICAO_Airlines.txt"
          
          if ! cmp --silent "$file1" "$file2" || ! cmp --silent "$file1" "$file3" || ! cmp --silent "$file1" "$file4"; then
            echo "ICAO_Airlines.txt files do not match!"
            exit 1
          fi
        shell: bash

      - name: Check if ICAO_Airports.txt files match
        run: |
          file1="UK/Data/Plugin/TopSky_NERC/ICAO_Airports.txt"
          file2="UK/Data/Plugin/TopSky_iTEC/ICAO_Airports.txt"
          file3="UK/Data/Plugin/TopSky_NODE/ICAO_Airports.txt"
          file4="UK/Data/Plugin/TopSky_NOVA/ICAO_Airports.txt"
          
          if ! cmp --silent "$file1" "$file2" || ! cmp --silent "$file1" "$file3" || ! cmp --silent "$file1" "$file4"; then
            echo "ICAO_Airports.txt files do not match!"
            exit 1
          fi
        shell: bash

      - name: Check if TopSkyAirspace.txt files match
        run: |
          file1="UK/Data/Plugin/TopSky_NERC/TopSkyAirspace.txt"
          file2="UK/Data/Plugin/TopSky_iTEC/TopSkyAirspace.txt"
          file3="UK/Data/Plugin/TopSky_NODE/TopSkyAirspace.txt"
          file4="UK/Data/Plugin/TopSky_NOVA/TopSkyAirspace.txt"
          
          if ! cmp --silent "$file1" "$file2" || ! cmp --silent "$file1" "$file3" || ! cmp --silent "$file1" "$file4"; then
            echo "TopSkyAirspace.txt files do not match!"
            exit 1
          fi
        shell: bash

      - name: Check if TopSkyAreas.txt files match
        run: |
          file1="UK/Data/Plugin/TopSky_NERC/TopSkyAreas.txt"
          file2="UK/Data/Plugin/TopSky_iTEC/TopSkyAreas.txt"
          file3="UK/Data/Plugin/TopSky_NODE/TopSkyAreas.txt"
          file4="UK/Data/Plugin/TopSky_NOVA/TopSkyAreas.txt"
          
          if ! cmp --silent "$file1" "$file2" || ! cmp --silent "$file1" "$file3" || ! cmp --silent "$file1" "$file4"; then
            echo "TopSkyAreas.txt files do not match!"
            exit 1
          fi
        shell: bash

      - name: Check if TopSkyCallsigns.txt files match
        run: |
          file1="UK/Data/Plugin/TopSky_NERC/TopSkyCallsigns.txt"
          file2="UK/Data/Plugin/TopSky_iTEC/TopSkyCallsigns.txt"
          file3="UK/Data/Plugin/TopSky_NODE/TopSkyCallsigns.txt"
          file4="UK/Data/Plugin/TopSky_NOVA/TopSkyCallsigns.txt"
          
          if ! cmp --silent "$file1" "$file2" || ! cmp --silent "$file1" "$file3" || ! cmp --silent "$file1" "$file4"; then
            echo "TopSkyCallsigns.txt files do not match!"
            exit 1
          fi
        shell: bash

      - name: Check if TopSkyCallsignsLocal.txt files match
        run: |
          file1="UK/Data/Plugin/TopSky_NERC/TopSkyCallsignsLocal.txt"
          file2="UK/Data/Plugin/TopSky_iTEC/TopSkyCallsignsLocal.txt"
          file3="UK/Data/Plugin/TopSky_NODE/TopSkyCallsignsLocal.txt"
          file4="UK/Data/Plugin/TopSky_NOVA/TopSkyCallsignsLocal.txt"
          
          if ! cmp --silent "$file1" "$file2" || ! cmp --silent "$file1" "$file3" || ! cmp --silent "$file1" "$file4"; then
            echo "TopSkyCallsignsLocal.txt files do not match!"
            exit 1
          fi
        shell: bash

      - name: Check if TopSkyCPDLC.txt files match
        run: |
          file1="UK/Data/Plugin/TopSky_NERC/TopSkyCPDLC.txt"
          file2="UK/Data/Plugin/TopSky_iTEC/TopSkyCPDLC.txt"
          file3="UK/Data/Plugin/TopSky_NODE/TopSkyCPDLC.txt"
          file4="UK/Data/Plugin/TopSky_NOVA/TopSkyCPDLC.txt"
          
          if ! cmp --silent "$file1" "$file2" || ! cmp --silent "$file1" "$file3" || ! cmp --silent "$file1" "$file4"; then
            echo "TopSkyCPDLC.txt files do not match!"
            exit 1
          fi
        shell: bash

      - name: Check if TopSkyCPDLChoppieCode.txt files match
        run: |
          file1="UK/Data/Plugin/TopSky_NERC/TopSkyCPDLChoppieCode.txt"
          file2="UK/Data/Plugin/TopSky_iTEC/TopSkyCPDLChoppieCode.txt"
          file3="UK/Data/Plugin/TopSky_NODE/TopSkyCPDLChoppieCode.txt"
          file4="UK/Data/Plugin/TopSky_NOVA/TopSkyCPDLChoppieCode.txt"
          
          if ! cmp --silent "$file1" "$file2" || ! cmp --silent "$file1" "$file3" || ! cmp --silent "$file1" "$file4"; then
            echo "TopSkyCPDLChoppieCode.txt files do not match!"
            exit 1
          fi
        shell: bash

      - name: Check if TopSkyMaps.txt files match
        run: |
          file1="UK/Data/Plugin/TopSky_NERC/TopSkyMaps.txt"
          file2="UK/Data/Plugin/TopSky_iTEC/TopSkyMaps.txt"
          file3="UK/Data/Plugin/TopSky_NODE/TopSkyMaps.txt"
          file4="UK/Data/Plugin/TopSky_NOVA/TopSkyMaps.txt"
          
          if ! cmp --silent "$file1" "$file2" || ! cmp --silent "$file1" "$file3" || ! cmp --silent "$file1" "$file4"; then
            echo "TopSkyMaps.txt files do not match!"
            exit 1
          fi
        shell: bash

      - name: Check if TopSkyMSAW.txt files match
        run: |
          file1="UK/Data/Plugin/TopSky_NERC/TopSkyMSAW.txt"
          file2="UK/Data/Plugin/TopSky_iTEC/TopSkyMSAW.txt"
          file3="UK/Data/Plugin/TopSky_NODE/TopSkyMSAW.txt"
          file4="UK/Data/Plugin/TopSky_NOVA/TopSkyMSAW.txt"
          
          if ! cmp --silent "$file1" "$file2" || ! cmp --silent "$file1" "$file3" || ! cmp --silent "$file1" "$file4"; then
            echo "TopSkyMSAW.txt files do not match!"
            exit 1
          fi
        shell: bash

      - name: Check if TopSkyRadars.txt files match
        run: |
          file1="UK/Data/Plugin/TopSky_NERC/TopSkyRadars.txt"
          file2="UK/Data/Plugin/TopSky_iTEC/TopSkyRadars.txt"
          file3="UK/Data/Plugin/TopSky_NODE/TopSkyRadars.txt"
          file4="UK/Data/Plugin/TopSky_NOVA/TopSkyRadars.txt"
          
          if ! cmp --silent "$file1" "$file2" || ! cmp --silent "$file1" "$file3" || ! cmp --silent "$file1" "$file4"; then
            echo "TopSkyRadars.txt files do not match!"
            exit 1
          fi
        shell: bash

      - name: All files match
        run: echo "All TopSky datafiles match across the instances."